version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/Server
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/Server
    owner: ubuntu
    group: ubuntu
    pattern: "**"
    mode: 755
    
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas : root
