version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/Server/zip
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    pattern: "**"
    mode: 755
    
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas : ec2-user
