spring:
  datasource:
    url: jdbc:h2:~/konkuk;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
