name: Deploy to Production
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build
        env:
          CI: ''
      - name: write S3 BUCKET NAME
        run: echo "BUCKET_NAME=${{secrets.BUCKET_NAME}}" >> application.yml
        working-directory: ./server/src/main/resources
      - name: write S3 ACCESS KEY
        run: echo "S3_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}" >> application.yml
        working-directory: ./server/src/main/resources
      - name: write S3 SECRET KEY
        run: echo "S3_SECRET_KEY=${{secrets.S3_SECRET_KEY}}" >> application.yml
        working-directory: ./server/src/main/resources
      - name: write GOOGLE_CLIENT_ID
        run: echo "GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}" >> application.yml
        working-directory: ./server/src/main/resources
      - name: write GOOGLE_CLIENT_SECRET
        run: echo "GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}" >> application.yml
        working-directory: ./server/src/main/resources
      - name: write GOOGLE_REDIRECT_URI
        run: echo "GOOGLE_REDIRECT_URI=${{secrets.GOOGLE_REDIRECT_URI}}" >> application.yml
        working-directory: ./server/src/main/resources
       
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://thanksd-cd
